// angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { FlagService } from './flag.service';
import { ProductService, Product } from './product.service';
import { environment } from 'src/environment/environment';

const userContext = {
  kind: 'user',
  key: 'abc123',
  email: 'abc123@gmail.com',
  plan: 'gold'
};

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [
    ProductService,
    FlagService,
    { provide: 'ldClientID', useValue: environment.ldClientID },
    { provide: 'ldContext', useValue: userContext }
  ]
})
export class AppComponent implements OnInit {
  private readonly purchaseEnabledFlag: string = "enable-purchasing";
  product: Product = { name: "", price: 0.00, url: "" };
  purchaseDisabled: boolean = true;

  constructor(private flagService: FlagService, private productService: ProductService) {
  }

  ngOnInit(): void {
    this.flagService.getFlagValue(this.purchaseEnabledFlag).then(value => {
      this.purchaseDisabled = !value;
    });

    this.flagService.subscribeToChanges(this.purchaseEnabledFlag, (value) => {
      this.purchaseDisabled = !value;
    });

    const randomProductId = [1, 2, 3, 4, 5][Math.floor(Math.random() * 5)];
    this.productService.getProduct(randomProductId, userContext.key, userContext.plan, userContext.email).subscribe(product => this.product = product);
  }

  getEmail() {
    return userContext.email;
  }

  getPlan() {
    return userContext.plan;
  }

  onPlaceOrderClick() {
    if (!this.purchaseDisabled) { alert('Thank you for your purchase.'); }
  }
}

<div class="main">
  <div class="row">
    <div class="column">
      <div class="product">
        <div class="productImage">
          <img [src]="product.url" />
          <div class="productDetails">
            <h3 class="productName">{{product.name}}</h3>
            <h2 class="productPrice">${{product.price | number:'1.2'}}</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="column">
      <div class="orderFormBox">
        <div class="orderForm">
          <h3 class="orderFormTitle">Angular Order Form</h3>
          <div class="input">
            <label>User's Email</label>
            <div class="orderInput">
              <input type="text" name="email" [value]="getEmail()" readonly="true" />
            </div>
          </div>
          <div class="input">
            <label>User's Plan</label>
            <div class="orderInput">
              <input type="text" name="plan" [value]="getPlan()" readonly="true" />
            </div>
          </div>
          <button class="orderButton" type="button" (click)="onPlaceOrderClick()" [disabled]="purchaseDisabled">Place
            order</button>
        </div>
      </div>
    </div>
  </div>
</div>

// react/src/App.js
import { useState } from 'react';
import { useFlags } from 'launchdarkly-react-client-sdk';
import './App.css';

export default function App(props) {
  const { enablePurchasing } = useFlags();
  const [context] = useState(props.context);

  const placeOrderClicked = () => {
    alert('Thank you for your purchase.');
  };

  const Product = (props) => (
    <div className="product">
      <div className="productImage">
        <img src={props.img} />
        <div className="productDetails">
          <h3 className="productName">{props.name}</h3>
          <h2 className="productPrice">${props.price.toFixed(2)}</h2>
        </div>
      </div>
    </div>
  );

  const Checkout = (props) => (
    <div className="orderFormBox">
      <div className="orderForm">
        <h3 className="orderFormTitle">React Order Form</h3>
        <Input label="User's Email" type="text" name="email" value={props.email} />
        <Input label="User's Plan" type="text" name="plan" value={props.plan} />
        <button className="orderButton" type="button" disabled={!enablePurchasing} onClick={placeOrderClicked}>Place Order</button>
      </div>
    </div>
  );

  const Input = (props) => (
    <div className="input">
      <label>{props.label}</label>
      <div className="orderInput">
        <input readOnly={true} type={props.type} name={props.name} value={props.value} onChange={() => { }} />
      </div>
    </div>
  );

  return (
    <div className="main">
      <div className="row">
        <div className="column">
          <Product name={context.name} price={context.price} img={context.url} />
        </div>
        <div className="column">
          <Checkout email={context.email} plan={context.plan}/>
        </div>
      </div>
    </div>
  );
}
